# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:categories/:year/:month/:day/:title 

# Setup
title:               逸
tagline:             ''
description:         '每有所得，欣然记之'
url:                 http://blog.fuzhii.com
baseurl:             'http://blog.fuzhii.com'
paginate:            5
author_thumbnail: "http://blog.fuzhii.com/assets/images/avatar.jpg" 

# About/contact
author:
  name:              Huang Yi
  url:               https://blog.fuzhii.com
  email:             ituzhi@163.com

# Custom vars
version:             1.0.0

comments :
