# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:categories/:year/:month/:day/:title 
relative_permalinks: true

# Setup
title:               逸
tagline:             'When lotus lush'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://blog.tuzhii.com
baseurl:             'http://blog.tuzhii.com'
paginate:            5

# About/contact
author:
  name:              Huang Yi
  url:               https://blog.tuzhii.com
  email:             ituzhi@163.com

# Custom vars
version:             1.0.0
