# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:categories/:year/:month/:day/:title 
relative_permalinks: true

# Setup
title:               逸
tagline:             '  When lotus lush'
description:         '如果你偶然记得关于桃花岛黄药师的传说，记得划船来找我。你往何处去，我在这儿等你。'
url:                 http://blog.tuzhii.com
baseurl:             'http://blog.tuzhii.com'
paginate:            5
author_thumbnail: "http://blog.tuzhii.com/assets/images/avatar.jpg" 

# About/contact
author:
  name:              Huang Yi
  url:               https://blog.tuzhii.com
  email:             ituzhi@163.com

# Custom vars
version:             1.0.0
