# Site settings
title: 涯余
tagline: 若得其情，哀矜勿喜
email: yanhangyhy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  十年饮冰，难凉热血
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://urbem.org" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "涯余"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: hangyan
    twitter: YanHangYuHaiYan
    facebook: yanhangyhy


  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key:

  disqus_shortname: yanhangyhy

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed



# excerpt_separator: <!--more-->
